services:
  fe-dashboard:
    container_name: fe-client-prod
    image: fe-client:prod

    build:
      context: .
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_ENCRYPT_KEY: ${NEXT_PUBLIC_ENCRYPT_KEY}
        ENCRYPT_SECRET_KEY: ${ENCRYPT_SECRET_KEY}
        NEXT_SITE_BASE_URL: ${NEXT_SITE_BASE_URL}
        
    ports:
      - '3000:3000'

    restart: unless-stopped
