services:
  fe-dashboard:
    container_name: fe-client-dev
    image: fe-client:dev

    build:
      context: .
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
        NEXT_PUBLIC_ENCRYPT_KEY: ${NEXT_PUBLIC_ENCRYPT_KEY}
        ENCRYPT_SECRET_KEY: ${ENCRYPT_SECRET_KEY}
        NEXT_SITE_BASE_URL: ${NEXT_SITE_BASE_URL}

    extra_hosts:
      - "dev-api.pakargaming.id:172.18.0.2"

    ports:
      - "3000:3000"

    restart: unless-stopped
