name: Deploy Dev PakarGaming Client

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy Client (Dev)
    runs-on: [self-hosted, dev]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy FE
        shell: bash
        run: |
          set -e

          echo "Workspace: $GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE"

          echo "Listing files"
          ls -la

          echo "ğŸ”¨ Building image..."
          
          echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL_DEV }}" >> .env
          echo "NEXT_PUBLIC_ENCRYPT_KEY=${{ secrets.NEXT_PUBLIC_ENCRYPT_KEY }}" >> .env
          echo "ENCRYPT_SECRET_KEY=${{ secrets.ENCRYPT_SECRET_KEY }}" >> .env
          echo "NEXT_SITE_BASE_URL=${{ secrets.NEXT_SITE_BASE_URL }}" >> .env


          if docker compose -f docker-compose.dev.yml build; then
            echo "âœ… Build success"

            echo "ğŸš€ Restarting container..."
            docker compose -f docker-compose.dev.yml up -d

            echo "ğŸ‰ Deploy success"
          else
            echo "âŒ Build failed!"
            echo "âš ï¸ Keeping previous container running"
            exit 1
          fi
