name: Deploy Prod PakarGaming Client

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Client  (Prod)
    runs-on: [self-hosted, main]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy FE
        shell: bash
        run: |
          set -e


          echo "Workspace: $GITHUB_WORKSPACE"
          cd "$GITHUB_WORKSPACE"

          echo "Listing files"
          ls -la
          export NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL_PROD }}
          export NEXT_PUBLIC_ENCRYPT_KEY=${{ secrets.NEXT_PUBLIC_ENCRYPT_KEY }}
          export ENCRYPT_SECRET_KEY=${{ secrets.ENCRYPT_SECRET_KEY }}
          export NEXT_SITE_BASE_URL=${{ secrets.NEXT_SITE_BASE_URL }}


          echo "üî® Building image..."
            if docker compose -f docker-compose.main.yml build; then
              echo "‚úÖ Build success"

              echo "üöÄ Restarting container..."
              docker compose -f docker-compose.main.yml up -d

              echo "üéâ Deploy success"
            else
              echo "‚ùå Build failed!"
              echo "‚ö†Ô∏è Keeping previous container running"
              exit 1
            fi
